version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_customer
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  mariadb:
    image: mariadb:11
    container_name: mariadb_service
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: service_order
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: service_payment
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mysql_data:
  mariadb_data:
  mongo_data:
